pipeline:
  type: Ingest

  location_id: myhouse2
  dataset_name: noisynoise
  qualifier: matlab
  temporal: 10Hz
  data_level: a1

dataset_definition:
  attributes:
    title: Example ingest of matlab generated noise data
    description: not very useful data, that's for sure
    conventions: "ME Data Pipeline Standards: Version 1.0"
    institution: Pacific Northwest National Laboratory
    code_url: https://github.com/emma-d-cotter/tsdat_local
    location_meaning: Morro Bay

  dimensions:
    time:
        length: unlimited

  variables:

    time:
      input:
        name: Var1
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%m/%d/%Y %H:%M:%S.%f"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    mass:
      input:
        name: Var2
        units: mg
      dims: [time]
      type: float
      attrs:
        long_name: mass
        description: "mass of the substance at the time"
        standard_name: mass
        units: mg
      #  fail_range: [0.0, 50.0]

#-----------------------------------------------------------------
quality_management:

  #---------------------------------------------------------------
  # manage_missing_coordinates:
  #   checker:
  #     classname: tsdat.qc.checkers.CheckMissing
  #   handlers:
  #     - classname: tsdat.qc.handlers.FailPipeline
  #   variables:
  #     - mass

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - time
 # ---------------------------------------------------------------
    manage_missing_values:
      checker:
        classname: tsdat.qc.checkers.CheckMissing
      handlers:
        - classname: tsdat.qc.handlers.RemoveFailedValues
        - classname: tsdat.qc.handlers.RecordQualityResults
          parameters:
            bit: 2
            assessment: Bad
            meaning: "Value is equal to _FillValue or NaN"
      variables:
        - DATA_VARS

  # manage_fail_min:
  #   checker:
  #     classname: tsdat.qc.checkers.CheckFailMin
  #   handlers:
  #     - classname: tsdat.qc.handlers.RecordQualityResults
  #       parameters:
  #         bit: 3
  #         assessment: Bad
  #         meaning: "Value is less than fail_range"
  #   variables:
  #     - mass

  # manage_fail_max:
  #   checker:
  #     classname: tsdat.qc.checkers.CheckFailMax
  #   handlers:
  #     - classname: tsdat.qc.handlers.RecordQualityResults
  #       parameters:
  #         bit: 999
  #         assessment: Bad
  #         meaning: "Value is greater than fail_range"
  #   variables:
  #     - mass
