pipeline:
  type: Ingest

  location_id: sequim
  dataset_name: testtide
  qualifier: tidegage
  temporal: 5min
  data_level: a1

dataset_definition:
  attributes:
    title: Sequim Tide Gage
    description: sequim tide gage data for SequimData project
    conventions: "ME Data Pipeline Standards: Version 1.0"
    institution: Pacific Northwest National Laboratory
    code_url: https://github.com/emma-d-cotter/tsdat_local
    location_meaning: Morro Bay

  dimensions:
    time:
        length: unlimited

  variables:

    time:
      input:
        name: time
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%Y-%m-%d %H:%M:%S,%f"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    elevation:
      input:
        name: data
        units: m
      dims: [time]
      type: float
      attrs:
        long_name: Tidal Elevation (m)
        description: "tidal elevation"
        standard_name: elevation
        units: m
        fail_range: [0.1, 15]

#-----------------------------------------------------------------
quality_management:

 # ---------------------------------------------------------------
    # manage_missing_coordinates:
    #   checker:
    #     classname: tsdat.qc.checkers.CheckMissing
    #   handlers:
    #     - classname: tsdat.qc.handlers.FailPipeline
    #   variables:
    #     - elevation

#   manage_coordinate_monotonicity:
#     checker:
#       classname: tsdat.qc.checkers.CheckMonotonic
#     handlers:
#       - classname: tsdat.qc.handlers.FailPipeline
#     variables:
#       - time
#  # ---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 3
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - elevation

  manage_fail_min:
    checker:
      classname: tsdat.qc.checkers.CheckFailMin
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 2
          assessment: Bad
          meaning: "Value is less than fail_range"
    variables:
      - elevation

  manage_fail_max:
    checker:
      classname: tsdat.qc.checkers.CheckFailMax
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is greater than fail_range"
    variables:
      - elevation
