
storage:
  classname:  tsdat.io.FilesystemStorage
  parameters:
    retain_input_files: False
    root_dir: /data/storage

  file_handlers:
    input:
      imu:
        file_pattern: '.*\.sta'
        classname: pipeline.filehandlers.StaFileHandler

    output:
      netcdf:
        file_extension: '.nc'
        classname: tsdat.io.filehandlers.NetCdfHandler
